name: Deploy Strapi App

on:
  push:
    branches:
      - main  # Set your default branch here

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install  # or use yarn

    - name: Build
      run: npm run build  # Adjust if you have a different build script

    - name: Copy files to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: ".
